language: java
jdk: openjdk8
sudo: true
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE quipv;'
  - cp src/main/resources/app.prop.github src/main/resources/application.properties
services:
- mysql